### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by doamatto** [doamatto/gulp-eslint#65]
**Describe the bug**
When executing, the following error appears:
```sh
...calculateStatsPerFile(messages)
^^^
SyntaxError: Unexpected token ...
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:549:28)
```

Cross-post of adametry/gulp-eslint#258 from @shouryamittal

**To Reproduce**
Node: 10.15.3
NPM: 6.4.1
Gulp CLI: 2.2.0
Gulp ESLint: 6.0.0 and 6.2.8.1

**Expected behavior**
Not this.

**Screenshots**
N/A

**Additional context**
The eslintrc file is:
```json
{ "env": { "node": true, "es6": true }, "parserOptions": { "ecmaVersion":2020, "ecmaFeatures": { "jsx": true } }, "settings": { "react": { "createClass": "createClass", "pragma": "React", "version": "detect" } }, //this config extends the eslint recommended and react presets. "extends":["eslint:recommended", "plugin:react/recommended"], //rules to be applied by eslint while validating the code. "rules": { "curly": "error", //enforce consistent brace style for all control statements "no-undef": "error", //disallow the use of undeclared variables unless mentioned in /*global */comments "no-unused-vars": "error", "no-trailing-spaces": "error", "semi": "error", //semicolons a must to end a statement "no-const-assign": "error", "eqeqeq": "error", //require the use of===and!== "no-extra-boolean-cast":"off" } }
```

**Comment by doamatto** [comment]
@shouryamittal Can you send over your Gulpfile.js so I can see how you're using the plugin?

**Comment by shouryamittal** [comment]
Hi Matt,
Sure, will do that.

**Comment by doamatto** [comment]
Hey @shouryamittal; it's been a few days. Just wanted to give a friendly reminder of sending over your Gulpfile.js.

Cheers!

**Comment by doamatto** [comment]
Hey @shouryamittal. I plan to close this issue in 2 days if I don't hear back by then. Obviously, you are free to re-open this issue with the case be or create a new one in this repo.

Cheers!
